### ISSUE TITLE
希望增加可以填入b站cookie，用以录制付费/加密直播间

### ISSUE THREAD

**Issue by KiraraV** [windowsair/bilibili_danmaku#11]

**Comment by windowsair** [comment]
叔叔的骚操作太多了，这个后续会考虑添加的

**Comment by windowsair** [comment]
现在有加密/付费的房间吗？这会儿好像没地方测试

**Comment by KiraraV** [comment]
> 现在有加密/付费的房间吗？这会儿好像没地方测试
今天9.30，631房间舰长限定

**Comment by KiraraV** [comment]
> 现在有加密/付费的房间吗？这会儿好像没地方测试

今天21:30，631房间舰长限定

**Comment by windowsair** [comment]
好的，我这会儿测试一下

**Comment by windowsair** [comment]
根据我这里的测试结果，不需要cookie也可以进行录制。后续这个可能会被封，那到时候再说吧

**Comment by windowsair** [comment]
等等，，，给的流好像还是假的，我再看看

**Comment by KiraraV** [comment]
> 等等，，，给的流好像还是假的，我再看看

昨天也有这样的一个舰长限定直播，试过B站录播姬、blrec不填cookie录不到实际直播内容，应该只是一段固定画面；填入cookie后才能录到实际内容的流

**Comment by windowsair** [comment]
好的，我这里搞清楚了，稍微修改一下就上库

**Comment by windowsair** [comment]
可以看下最新版本是否解决问题。已经在上述直播间测试过了
https://github.com/windowsair/bilibili_danmaku/releases/tag/v0.0.21

**Comment by windowsair** [comment]
看起来没啥问题了，准备关闭这个issue，欢迎随时再打开它
