### ISSUE TITLE
无法录制

### ISSUE THREAD

**Issue by pongfcnkl** [windowsair/bilibili_danmaku#13]
部分主播能录制
![截图_20230512174644](https://github.com/windowsair/bilibili_danmaku/assets/24273319/0e3689b0-000c-41ba-8432-10999ddcc84a)

大部分主播都是 无法与直播流建立连接，重试 段错误
![截图_20230512173631](https://github.com/windowsair/bilibili_danmaku/assets/24273319/f6a0c6c7-02d0-483a-884d-31bb3590d43f)
windows这里直接停止工作了
![截图_20230512174200](https://github.com/windowsair/bilibili_danmaku/assets/24273319/3128460b-ebaa-45cf-8f6a-d2a5019cf44c)

**Comment by windowsair** [comment]
windows的是什么情况，直接无法打开吗

**Comment by windowsair** [comment]
也是像ubuntu一样直接退出吗？

**Comment by windowsair** [comment]
您好，可以试试这个版本
https://github.com/windowsair/bilibili_danmaku/releases/tag/v0.0.24

**Comment by windowsair** [comment]
看起来没啥问题，准备关闭这个issue了，欢迎随时再打开它
