### ISSUE TITLE
作者大大，请问下这个参数！

### ISSUE THREAD

**Issue by holwell** [windowsair/bilibili_danmaku#14]
```
"font_alpha_fix": true,
    "#font_alpha_fix": [ "为false时，采用默认的alpha混合策略（速度优先）。弹幕可能变暗，尤其是当不透明度小于0.6时",
```
请问下这个参数是在ffmpeg里添加某个参数进行压制的吗，我想用原生ffmpeg的命令压制，但是透明度50%就很暗淡...
![008CFD52](https://github.com/windowsair/bilibili_danmaku/assets/45387795/ef9f34ac-9a17-48b8-b32c-bad0c2a66370)
救救救！

**Comment by windowsair** [comment]
这个参数目前已经弃用了，不管设置成什么都是一样的效果。

目前live_render渲染出来的透明度效果，应该是和直接使用ffmpeg压制ass文件保持一致的。

**Comment by holwell** [comment]
好的，感谢作者大大的回复，么么😘另外的话，能否偷偷推荐一个绝佳好用的透明度、字体大小、描边大小的压制参数！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月8日(周二) 中午12:48
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [windowsair/bilibili_danmaku] 作者大大，请问下这个参数！ (Issue #14)




 
这个参数目前已经弃用了，不管设置成什么都是一样的效果。
 
目前live_render渲染出来的透明度效果，应该是和直接使用ffmpeg压制ass文件保持一致的。

**Comment by windowsair** [comment]
不知道你有没有用过aegisub，你可以直接在aegisub上设置这些参数并预览效果。

如果要现成参数的话，晚上我回去看看录播组的文件还在不在

**Comment by holwell** [comment]
> 

再次感谢作者大大啦，我自己去摸索一下，不用特地麻烦啦！

**Comment by holwell** [comment]
> 

再次感谢作者大大啦，我自己去摸索一下，不用特地麻烦啦！

**Comment by windowsair** [comment]
```json
    "font_family": "HYQiHei-65S",
    "#font_family": "采用的字体集",

    "font_scale": 1.8,
    "#font_scale": "字体缩放倍数，为1.0时保持原始大小（基础字号为25）",

    "font_alpha": 0.5,
    "#font_alpha": "字体不透明度,取值为0~1.0,为0时完全透明",

    "font_alpha_fix": false,
    "#font_alpha_fix": [ "为false时，采用默认的alpha混合策略（速度优先）。弹幕可能变暗，尤其是当不透明度小于0.6时",
        "为true时，采用符合自觉的alpha混合策略（质量优先），但是会降低渲染速度",
        "根据对渲染效果和渲染速度的要求选择合适的项目。"
    ],

    "font_bold": true,
    "#font_bold": "是否设置字体加粗,true加粗,false不加粗",

    "font_outline": 0.4,
    "#font_outline": "字体描边（边框）值",

    "font_shadow": 0.0,
    "#font_shadow": "字体阴影值",
```

以上是录播组的配置，供您参考。

另外提醒下，如果发现低的透明度下弹幕发黑，那么可能是用的ffmpeg版本太老，请使用2022.5.12以后的版本的ffmpeg

**Comment by holwell** [comment]
好的，再次感谢您的宝贵建议和热心帮助！么么😘



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月8日(周二) 晚上8:46
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [windowsair/bilibili_danmaku] 作者大大，请问下这个参数！ (Issue #14)




     "font_family": "HYQiHei-65S",     "#font_family": "采用的字体集",     "font_scale": 1.8,     "#font_scale": "字体缩放倍数，为1.0时保持原始大小（基础字号为25）",     "font_alpha": 0.5,     "#font_alpha": "字体不透明度,取值为0~1.0,为0时完全透明",     "font_alpha_fix": false,     "#font_alpha_fix": [ "为false时，采用默认的alpha混合策略（速度优先）。弹幕可能变暗，尤其是当不透明度小于0.6时",         "为true时，采用符合自觉的alpha混合策略（质量优先），但是会降低渲染速度",         "根据对渲染效果和渲染速度的要求选择合适的项目。"     ],     "font_bold": true,     "#font_bold": "是否设置字体加粗,true加粗,false不加粗",     "font_outline": 0.4,     "#font_outline": "字体描边（边框）值",     "font_shadow": 0.0,     "#font_shadow": "字体阴影值",
 
以上是录播组的配置，供您参考。
 
另外提醒下，如果发现低的透明度下弹幕发黑，那么可能是用的ffmpeg版本太老，请使用2022.5.12以后的版本的ffmpeg
