### ISSUE TITLE
开播时不自动开始录制

### ISSUE THREAD

**Issue by luminousx1** [windowsair/bilibili_danmaku#16]
版本为0.0.25，提前打开录制的话开播时大概率没反应，似乎只有马上开播时候打开才能正常录，而且也有可能录了但是弹幕没有压制到视频里
![a9d83ba40bd5da29392e7d5d3c03ddb6](https://github.com/windowsair/bilibili_danmaku/assets/107185023/25b13345-f097-44d3-9f42-87e72983de97)
图中是下午四点左右打开的录制，七点开播时没有开始

**Comment by windowsair** [comment]
感谢反馈，最近弹幕系统似乎有更新，我尽快修复下

**Comment by windowsair** [comment]
您好，可以试试最新的0.0.26版本
https://github.com/windowsair/bilibili_danmaku/releases/tag/v0.0.26

**Comment by luminousx1** [comment]
已测试，运行正常，感谢！
