### ISSUE TITLE
边录边压音视频长度不一致

### ISSUE THREAD

**Issue by luminousx1** [windowsair/bilibili_danmaku#2]
昨晚的录播发到B站时候一直提示音视频长度不一致，转码失败
用losslesscut切掉最后1~2个关键帧后还是不行
但ffmpeg分离音视频后长度一致（附日志）
[live_render_1654689091886.log](https://github.com/windowsair/bilibili_danmaku/files/8869487/live_render_1654689091886.log)

**Comment by windowsair** [comment]
是不是换机器了，看起来这台机器的性能不太够

**Comment by luminousx1** [comment]
没有换机器，但是昨晚同时开了两个边录边压（另一个在监控但是没开始录制），还有录播姬和blrec

**Comment by windowsair** [comment]
看起来是小概率事件。再观察几天，如果还是这样的话切换到新的版本，到时候我会发个新的配置出来

**Comment by windowsair** [comment]
最近还有其他问题吗？如果没有的话，让我们关闭这个问题
