### ISSUE TITLE
可以给xml2ass添加对弹幕黑名单的支持吗

### ISSUE THREAD

**Issue by YRFBK** [windowsair/bilibili_danmaku#4]
如题，实时压制偶尔会出现延迟过大的问题，想用弹幕文件重新压制时发现xml2ass无法应用弹幕黑名单
可以的话十分感谢

**Comment by windowsair** [comment]
最新的版本增加了这个功能
https://github.com/windowsair/bilibili_danmaku/releases/tag/v0.0.18

**Comment by YRFBK** [comment]
好快的加，感谢！~
