### ISSUE TITLE
录制过程中卡住，命令行仍在运行，但视频长度已不变

### ISSUE THREAD

**Issue by luminousx1** [windowsair/bilibili_danmaku#5]
![LRF@NX32FRFO%8)@LUTMA~U](https://user-images.githubusercontent.com/107185023/189536754-1e693ecc-9317-404b-a14e-b24f7be811d8.png)
如图，附日志
[live_render_1662899311623.log](https://github.com/windowsair/bilibili_danmaku/files/9542928/live_render_1662899311623.log)

**Comment by windowsair** [comment]
看起来又是b站的推流问题😥

**Comment by luminousx1** [comment]
今天确实好几个人都断了，不过昨天也遇到过同样的问题，当时其他人并没有断。
不过当时我同时开着游戏，可能是cpu或者内存占满了？

**Comment by windowsair** [comment]
有之前的日志嘛，看看是什么问题

**Comment by luminousx1** [comment]
这是前一天的
[live_render_1662809126107.log](https://github.com/windowsair/bilibili_danmaku/files/9548019/live_render_1662809126107.log)

**Comment by windowsair** [comment]
看起来同样是推流的问题

**Comment by windowsair** [comment]
好像抓到的cdn就特别差，一开始就出现推流问题了

**Comment by luminousx1** [comment]
那应该是推流那边的问题，主播最近被隔离，网络不太稳定
