### ISSUE TITLE
直播标题中带emoji后无法开始录制

### ISSUE THREAD

**Issue by luminousx1** [windowsair/bilibili_danmaku#6]
附日志，有时无法获取房间id，但即使获取到了也会自动退出，猜测是直播标题带了emoji？
[live_render_1663844617685.log](https://github.com/windowsair/bilibili_danmaku/files/9625038/live_render_1663844617685.log)
![5RM106P$VPHYUCVZ10 D 1Q](https://user-images.githubusercontent.com/107185023/191730998-51cc35e6-60cb-4cb3-ada3-223306e3c677.png)
![{(277501_U11B98O9K8LQVF](https://user-images.githubusercontent.com/107185023/191731012-b832fd7b-f046-4ad7-b628-9c78f1ac0a84.png)

**Comment by windowsair** [comment]
b站现在居然开始做反爬了

**Comment by windowsair** [comment]
久等了，新版本应该修复了这个问题

https://github.com/windowsair/bilibili_danmaku/releases/tag/v0.0.19
